# Generated by Django 4.1.7 on 2023-04-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IAC', models.CharField(max_length=8)),
                ('DepCode', models.CharField(max_length=8)),
            ],
        ),
    ]
