# Generated by Django 4.1.7 on 2023-03-15 15:56

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('shopping_bag', models.IntegerField(default='0', validators=[shop.models.validate_positive])),
                ('current_account', models.IntegerField(validators=[shop.models.validate_positive])),
                ('credit_limit', models.IntegerField(validators=[shop.models.validate_positive])),
                ('current_doubt', models.IntegerField(default='0', validators=[shop.models.validate_positive])),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[shop.models.validate_positive])),
                ('stock_balance', models.IntegerField(validators=[shop.models.validate_positive])),
            ],
        ),
    ]
